package stateMachine.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Event = 0;
  public static final int State = 1;
  public static final int StateMachine = 2;
  public static final int Transition = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd8a98e10b8d746b5L, 0xbba34a75c192be91L);
    builder.put(0x4282f79c2914f836L, Event);
    builder.put(0x4282f79c2914ff5dL, State);
    builder.put(0x4282f79c29141f54L, StateMachine);
    builder.put(0x4282f79c2915142fL, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
